export const OBTENER_OPERACIONES = 'OBTENER_OPERACIONES';
export const AGREGAR_OPERACIONES = 'AGREGAR_OPERACIONES';
export const EDITAR_OPERACIONES = 'EDITAR_OPERACIONES';
export const BORRAR_OPERACIONES = 'BORRAR_OPERACIONES';
export const OPERACION_ACTUAL = 'OPERACION_ACTUAL';

export const ERROR_OPERACIONES = 'ERROR_OPERACIONES';
export const MENSAJE_NULL = 'MENSAJE_NULL';
export const MOSTRAR_BALANCE = 'MOSTRAR_BALANCE';

export const ENVIAR_LOGIN = 'ENVIAR_LOGIN';
export const ENVIAR_REGISTRO = 'ENVIAR_REGISTRO';

export const REGISTRO_EXITOSO = 'REGISTRO_EXITOSO';
export const REGISTRO_ERROR = 'REGISTRO_ERROR';
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGIN_EXITOSO = 'LOGIN_EXITOSO';
export const USUARIO_AUTENTICADO = 'USUARIO_AUTENTICADO';
export const CERRAR_SESION = 'CERRAR_SESION';


    