export const OBTENER_OPERACIONES = 'OBTENER_OPERACIONES';
export const AGREGAR_OPERACIONES = 'AGREGAR_OPERACIONES';
export const EDITAR_OPERACIONES = 'EDITAR_OPERACIONES';
export const BORRAR_OPERACIONES = 'BORRAR_OPERACIONES';
export const OPERACION_ACTUAL = 'OPERACION_ACTUAL';

export const ERROR_OPERACIONES = 'ERROR_OPERACIONES';
export const MENSAJE_NULL = 'MENSAJE_NULL';
export const MOSTRAR_BALANCE = 'MOSTRAR_BALANCE';
